### ISSUE TITLE
review "webwires" edits

### ISSUE THREAD

**Issue by ianlopez1115** [OSMPH/papercut_fix#39]
I've noticed that [webwires'](http://www.openstreetmap.org/user/webwires) "rewiring" of Metro Manila, Cavite, Iloilo and Capiz left a significant mess, specifically the deletion of important POIs such as bus stops and mangling of highways and public transit data. A set of reverts have been done in December 2017, but are mostly focused on road routing and admin boundaries if I'm not mistaken.

Please take note that the user in question is deleting and recreating data ([shown here](https://nrenner.github.io/achavi/?changeset=56863576#map=16)), which is a very bad practice.

## TODO

- [ ] review changesets
- [ ] attempt to contact the mapper, for action and rectification
- [ ] inform OSM Philippines mailing list of plans: if no action is made by the mapper by March 11, the covered mapper's harmful changesets will be thoroughly reverted.
- [ ] revert harmful changesets

**Comment by govvin** [comment]
Ian, may I also suggest you try leave changeset comments during your review? That could be helpful, in case DWG has to get involved. 

We've had other concerns with this particular user, and they are not known to respond to comments and direct messages.

**Comment by seav** [comment]
> We've had other concerns with this particular user, and they are not known to respond to comments and direct messages.

I sent a couple of direct messages to this user and he did respond favorably to both messages. But I agree that I have never seen him respond to changeset comments.

**Comment by TagaSanPedroAko** [comment]
[This changeset](https://www.openstreetmap.org/changeset/54625256#map=14/14.6512/121.0340) is one proof of his disruptive editing, as you see, the polygon for Trinoma is deleted as part of those "rewiring". We should keep track of his editing as there are those being obviously disruptive.

**Comment by govvin** [comment]
DWD gave this user a zero-hour block, after their attempt to communicate with him was ignored.

https://www.openstreetmap.org/user/webwires/blocks
