### ISSUE TITLE
Roll-back changesets of administrative boundaries for edits based on incompatible source

### ISSUE THREAD

**Issue by govvin** [OSMPH/papercut_fix#67]
**This ticket is for tracking the roll-back of several changesets which added admin_level relations from a source with an incompatible license. </p> This is a community initiative to clean-up the data, please add your name if you want to help.**

#### Context

Someone from the mailing list posted a query about admin boundaries in [Alaminos City being dissimilar](https://lists.openstreetmap.org/pipermail/talk-ph/2020-June/006591.html) compared against their knowledge, and was inquiring for more information.

The question triggered a wider review of related edits, and after a re-examination and the contributor's [corroboration](https://user-images.githubusercontent.com/5821688/86066157-00db5b00-baa4-11ea-953c-d27636575dc4.png), it is confirmed that the data source has an incompatible license with OpenStreetmap.  We had a dialog with the contributor, and they provided us a list of changesets related to these edits and a [request](https://user-images.githubusercontent.com/5821688/86083276-5f1c3400-bacc-11ea-8227-3e5e3064e451.png) for help with rolling back said edits.

#### Next actions
This rollback will come in two phases:
- [x] **[Phase 1](https://github.com/OSMPH/papercut_fix/issues/67#issuecomment-655266926)** - remove all `admin_level` relations and `place nodes` created from incompatible sources (PSGC, Project NOAH).
- [x] **[Phase 2](https://github.com/OSMPH/papercut_fix/issues/67#issuecomment-665568730)** - replicate admin boundaries (province, region) using Wikipedia Maps.  Remove any elements (nodes, ways) added by the user, and fill gaps by extending the ways from the previous, valid version.
- [x] **[Phase 3]()** - validation and clean-up

#### Why was this data uploaded to OpenStreetMap?

The data is available for "free" from various government websites, and states that they are _free to use by the public under non-commercial terms_. This is a commonly misinterpreted as "OK for importing to OpenStreetMap" by users. As a community, we decided in the past that unless there is explicit permission or a waiver of rights from data owners under such license, we should not add them in OSM.

**We wish to emphasize that we found no malicious intent by the contributor, as determined in our private conversations with them. The technical aspect of the edits is good, but the misunderstanding about the license is unfortunate.**

#### Rolling-back data is a lot of work, why not ask the OSM Data Working Group (DWG) for assistance?

The DWG will be advised of the on-going effort, however, as a comunity, we prefer this review and clean-up process to be done by the local volunteers. As a local community, we should be able to respond to such incidents, and avoid burdening the DWG unnecessarily, especially if issues can be addressed at the local level.

#### Will rolling-back these changesets affect my own contributions?

We did a couple of simulated roll-back, in most cases, there will be a clean roll-back.  

However, in the small chance that any other contributions are  inadvertently affected, we hope to ensure the data integrity through a manual review of changesets by volunteers after the roll-back operations.
 
Please use the changeset discussions, to discuss specific issues related to any affected changeset.

#### Updates
- July 29, 2020 - Proceed with Phase 2 workflow
- July 8, 2020 - New workflow in 2 phases.
- July 7, 2020 - Stopped previous workflow.
<details>
 <summary>Previously abandoned workflow</summary>

- [x] Simulate roll-back for several changesets using the `revert.pl` script from [osm-revert-scripts](https://github.com/woodpeck/osm-revert-scripts/). @maning
- [x] Share this plan to talk-ph mailing list, OSMPH LoCos telegram and DWG contact email.
- [x] Incorporate any comments/suggestions from the community after review of this plan.
- [x] Roll-back each changeset starting from the most recent in descending order.  With the following changeset comment: `Rolled-back because source data license is incompatible with OSM. For details: github.com/OSMPH/papercut_fix/issues/67`
  - [x] 87152111
  - [x] 87100379 
  - [x] 87010401
  - [x] 87009673 
  - [x] 86987045
  - [x] 86975870 
  - [x] 86915142
  - [x] 86913549 
  - [x] 86746044 
  - [x] 86614562
  - [x] 86614381 
  - [x] 86602290 
  - [x] 86602275 
- [x] Post-roll-back manual cleanup.

</details>

**Comment by maning** [comment]
No comments from the OSM community (both in talk-ph list, telegram and this ticket).  We will proceed with the rollback using [OSMPilipinas-PaperCut-Fix](https://www.openstreetmap.org/user/OSMPilipinas-PaperCut-Fix/) account.

**Comment by maning** [comment]
Since yesterday, I was able to rollback 10 changesets.  The rollback process is slow as it checks each feature to the db before doing any action.  On the average, a feature is processed at 2.35 seconds.  For large changesets, this can take some time.  The good thing with the revert.pl script is that it continuous the process even if some features cannot be rolled-back due to various reasons.  This is different from other scripts I used so far which simply stops the process.

My main concern with this process is that as I go through the more changesets, more features seems to be not getting rolled-back primarily because I already touched them in a previous changeset (see screenshot).

<img width="907" alt="Screenshot 2020-07-05 21 41 05" src="https://user-images.githubusercontent.com/353700/86534116-65fdd900-bf08-11ea-9b18-704b77e01633.png"><br> _Relations that were not reverted because it was touched by another user, in this case our rollback account._

<img width="669" alt="Screenshot 2020-07-05 21 35 05" src="https://user-images.githubusercontent.com/353700/86534147-96de0e00-bf08-11ea-93f0-730ae643f7f0.png"><br> _Less features getting rollback as we go from descending date of changeset._

 @govvin @seav Need your advice here, should I continue this process?  The amount of time to rollback each feature remains the same (2.35 sec/feature) even if they don't rolledback dur to certain conditions.

**Comment by govvin** [comment]
I suspected these scenarios to happen with bigger relations (admin_levels < 7) where only a few elements has been touched in the the modification being rolled back, though I didn't expect it would take that much time per changeset, but this script's prudent approach to check all elements instead of just what just changed will be the reason for that lengthy operation.

The much cleaner roll-backs will probably happen with admin_level > 7 relations.

I propose that we proceed with this approach but also wonder if we can split the changeset list and run some of the revert scripts in parallel?


@maning  , do you have different expectations?

**Comment by maning** [comment]
> The much cleaner roll-backs will probably happen with admin_level > 7 relations.

I have the same assumption, however if you check this example:

Original | Rollback
---|---
<img width="1180" alt="Screenshot 2020-07-06 10 54 08" src="https://user-images.githubusercontent.com/353700/86551369-6da89680-bf77-11ea-8ebc-6e99f9f53d75.png">|<img width="1176" alt="Screenshot 2020-07-06 10 54 19" src="https://user-images.githubusercontent.com/353700/86551405-8add6500-bf77-11ea-918e-445ee51cbe04.png">
[86975870](https://osmcha.org/changesets/86975870/)|[87545874](https://osmcha.org/changesets/87545874)

By reverting this changeset, I expected that all **[admin_level=10 created features will be reverted however, since it was touched in a later changeset and consequently touched by our rollback account, it was not rolled-back](https://pewu.github.io/osm-history/#/relation/11226241).**

> I propose that we proceed with this approach but also wonder if we can split the changeset list and run some of the revert scripts in parallel?

OK.  I'm planning to run a shell script to rollback in batches say 10 in descending order and run it overnight.  I babysat the first 10 to make sure nothing unexepected will happen

**Comment by govvin** [comment]
I know you're keeping logs, those elements that failed the roll-back should be one of the things the volunteers will have to review in the post-rollback operations.

**Comment by seav** [comment]
I think we need to do a change of tactic here. If the script will not roll-back an OSM element if it has already been touched since the changeset that is being rolled back, including by our rollback user account, we won't be getting anywhere.

I suggest that instead of doing it on a changeset basis, we compile a list of municipalities and cities (`admin_level=6`) that are affected and then manually roll back per each LGU. This would may mean that we simply delete all barangay/city/municipality boundary relations and member ways or roll back to the version if any boundary existed before this issue. This would require doing an introspection on the history of each LGU.

I also suggest downloading the [March 1](http://download.geofabrik.de/asia/philippines-200301-free.shp.zip) extract from Geofabrik (which is the latest extract that predates all of these changesets), and use that as a source for the latest "clean" version of the boundaries.

I imagine that after this issue is resolved, we go back to the state where we have the provincial boundaries as of early March, and most (>95%) of the city/municipality/barangay boundary relations gone except for those boundaries that already previously existed (such as the municipality of Santa Ana, Cagayan).

**Comment by maning** [comment]
There's also this tool available in the revert-scripts: 

> complex_revert.pl           -- reverts a group of interdependent changesets

**Comment by seav** [comment]
Addendum: the earliest 4 changesets **do not** state "Project NOAH" as a source. The earliest two changesets even indicate Baguio's CLUP as the source which I consider as compatible. I think we should clarify these 4 changesets with the changeset user.

**Comment by seav** [comment]
> There's also this tool available in the revert-scripts:
> 
> > complex_revert.pl           -- reverts a group of interdependent changesets

Hmmm. Maybe we should have used this in the first place? But given the sheer number of changesets, I think this would go horribly wrong somewhere and not to mention take a long time to complete (like several days).

**Comment by maning** [comment]
> Addendum: the earliest 4 changesets do not state "Project NOAH" as a source. The earliest two changesets even indicate Baguio's CLUP as the source which I consider as compatible. I think we should clarify these 4 changesets with the changeset user.

But I did touch features with the [incompatible source](https://pewu.github.io/osm-history/#/relation/10996499).

**Comment by seav** [comment]
@maning;

> > Addendum: the earliest 4 changesets do not state "Project NOAH" as a source. The earliest two changesets even indicate Baguio's CLUP as the source which I consider as compatible. I think we should clarify these 4 changesets with the changeset user.
> 
> But it did touched features with the [incompatible source](https://pewu.github.io/osm-history/#/relation/10996499).

@maning, can you clarify? In the link you provided, the earliest changeset there is 83547233 which is not one of the four changesets that I indicated.

**Comment by seav** [comment]
I asked the user and this is their reply: "For Baguio-La Trinidad boundaries it uses all three sources with PSA not indicated in source."

**Comment by maning** [comment]
> @maning, can you clarify? In the link you provided, the earliest changeset there is 83547233 which is not one of the four changesets that I indicated.

Capturing discussion in telegram for posterity here:

<img width="694" alt="Screenshot 2020-07-06 13 59 26" src="https://user-images.githubusercontent.com/353700/86560524-07307200-bf91-11ea-95b0-e482226377f1.png">

**Comment by maning** [comment]
> I suggest that instead of doing it on a changeset basis, we compile a list of municipalities and cities (admin_level=6) that are affected and then manually roll back per each LGU. This would may mean that we simply delete all barangay/city/municipality boundary relations and member ways or roll back to the version if any boundary existed before this issue. This would require doing an introspection on the history of each LGU.
> I also suggest downloading the March 1 extract from Geofabrik (which is the latest extract that predates all of these changesets), and use that as a source for the latest "clean" version of the boundaries.

@seav Can you outline an actual step-by-step workflow (how to delet/rollback, how do we task each feature, extracting March 1 dump).  I'm happy to test.

**Comment by seav** [comment]
@maning: Here's a possible recipe:

1. Analyze all changesets and extract a list of all admin boundaries that were modified (they are all tagged with PSGC for convenience).
2. Group all barangays by city/municipality and all of those by province and make a 2-level checklist (province then city/municipality).
3. Each volunteer takes a city or municipality, inspects the history of all boundaries inside, and then delete boundaries that have been added or roll back to a previous clean version for modified boundaries (maybe using the March extract as a guide). In my estimation, I think that 99% of all barangays are "floating" in OSM and are not connected to any other OSM object and can just be safely deleted.

This will definitely be much, much more labor-intensive than using the revert scripts, but I really don't see how we can cleanly roll back the edits and we would be doing the labor-intensive review afterwards anyway.

**Comment by govvin** [comment]
If this is the approach to be taken, it might be easier to use level 0 on straight-forward roll backs for admin_levels < 7 with subsequent edits, check the date and version, and restore the version before the data with incompatible licensed was added. 

For example, see osm.org/wiki/Level0#Revert_a_node_to_a_previous_version , should work for other element types.

**Comment by govvin** [comment]
On second thought, I think a manual review will still end-up as the most expeditious way of doing this. 

Let's work on getting that check list by municipality and province affected by this.

**Comment by maning** [comment]
<img width="1089" alt="Screenshot 2020-07-06 14 50 13" src="https://user-images.githubusercontent.com/353700/86564062-1c5ccf00-bf98-11ea-8db1-fae49cfc3a80.png">
Here's the overpass query which I think covers most the source tags that was incompatible.  We can probbaly split this by province/town then assign people.

```
[out:xml][timeout:1000];
// fetch area “Philippines” to search in
{{geocodeArea:"Philippines"}}->.searchArea;
// gather results
(
  // query part for: “amenity=school”
  nwr["admin_level"]["source"="Project NOAH, PSGC"](area.searchArea);
  nwr["admin_level"]["source"="Project NOAH"](area.searchArea);
  nwr["admin_level"]["source"="PSGC"](area.searchArea);

);
// print results
out meta;
>;
out meta qt;
```

> previous clean version for modified boundaries (maybe using the March extract as a guide).

This is not very clear to me how do we actually do this?

**Comment by VMPanes** [comment]
@govvin Here's the list for all the municipalities with incompatible source. boundary_admin3to6.txt covers region to municipality/city while boundary_admin3to10.txt covers until barangays. Data pulled from relations. 
[boundary_admin3to10.txt](https://github.com/OSMPH/papercut_fix/files/4878158/boundary_admin3to10.txt)
[boundary_admin3to6.txt](https://github.com/OSMPH/papercut_fix/files/4878160/boundary_admin3to6.txt)

**Comment by maning** [comment]
Based on @seav's [proposal](https://github.com/OSMPH/papercut_fix/issues/67#issuecomment-654035539), we will stop automated rollback and will do this manually.  New process/workflow will be updated in the OP.

**Comment by maning** [comment]
#### Phase 1:  Review all admin relations by municipality/city.  Manually delete relations and its members that came from incompatible source.

1. Go to this **[tracker spreadhseet](https://docs.google.com/spreadsheets/d/1Jxh6Mg6mG07WGY3doy1L5gktue2n7oEAXIOrvT7aFcA/edit#gid=0)**, pick a municipality/city to work on by adding your name in the **User** column. Update the status to **In progress**. Refer to the map, and make sure to select a task with _no shared boundary_ to a task in progress
2. Open JOSM, make sure [JOSM Remote Control](https://wiki.openstreetmap.org/wiki/JOSM/RemoteControl) is enabled.
3. Click the JOSM-RC link in your assigned municipality/city.  This will download all relations (parent/child) within the  municipality/city.
4. Find and delete barangay boundary relations using the JOSM search filter `type:relation admin_level=10`.
5. Check the relation history to ensure that you only delete relation that was originally added by user VMPanes containing incompatble source (Select relation > Ctrl + h). 
![add sample screenshot](https://user-images.githubusercontent.com/353700/86869795-c6a83400-c109-11ea-9df2-1489dbcb865a.png)<br>*v1 of this relation contains incompatible source, this should be deleted.*
6. Find and delete orphaned/untagged ways using JOSM search filter: `untagged -child`
7. Review and modify/delete `place` nodes added from an invalid source. There may be cases where you only need to delete tags, and not the element itself.  Common scenarios are the following:

|Image|Scenario/Action
---|---
![](https://user-images.githubusercontent.com/353700/86869784-c019bc80-c109-11ea-8f49-452870a3de7f.png) | v1 came from incompatible source.<br> **Action**: Delete the place node.
![](https://user-images.githubusercontent.com/353700/86869791-c4de7080-c109-11ea-919e-1e9019551e04.png) | v8 and later contain incompatible source.<br> **Action**: Fix tags to retain v7 information, such as: <br>- adding back `is_in` (red); <br>- removing `admin_level`, `admin_type:ph`, `ref` (green); <br>- modify `source` (beige).
<img width="400" alt="Screenshot 2020-07-08 10 55 54" src="https://user-images.githubusercontent.com/353700/86870542-2bb05980-c10b-11ea-827a-546b73f4d76f.gif"><br><img width="400" alt="Screenshot 2020-07-08 10 55 54" src="https://user-images.githubusercontent.com/353700/86871055-1ab41800-c10c-11ea-90c5-21c1581e7add.png"> | Place node moved to a new location.  <br>**Action**: The **Coordinates** within the History dialog shows the difference of location for each changeset.  Move back the location to desired version (v7) by: <br> -  dragging the node in the main map or; <br> - use the **Move node** tool (Tool > Move) by copying the coordinates from v7.

8.  Run JOSM validator and fix any errors related to the boundary relations.
9. Upload your changes using the changeset comment: 
`Rolled-back because source data license is incompatible with OSM. For details: github.com/OSMPH/papercut_fix/issues/67`
11. Mark your task as in the spreadsheet as complete.  Add notes in the spreadsheet, as needed.  If you cannot complete the whole municipality, upload the data in OSM anyway.  Do not save locally to avoid conflict from other mappers.  **When you want to start again, always download fresh data via the spreadsheet tracker.**

**Comment by ianlopez1115** [comment]
Query originally posted in Telegram covering river segments that originally contained data from incompatible source, this also applies to streets and other conflated elements ![image](https://user-images.githubusercontent.com/1140532/86890363-c7ec5780-c12f-11ea-83d1-f1b08d65cd5e.png)

**Comment by seav** [comment]
Tip: you can select N place node/relations and then press `Ctrl-H` to open N history dialog boxes. I think this makes it easy to quickly review the history of a set of objects. Instead of selecting one at a time then pressing `Ctrl-H` for each one individually.

**Comment by govvin** [comment]
If you're not keen on cluttering your JOSM workspace with too many dialog boxes, try using the [Todo List](https://wiki.openstreetmap.org/wiki/JOSM/Plugins/TODO_list) plug-in for JOSM. 

It will let you create a task list you can conveniently cycle through. Also, by re-setting the OSM History shortcut (crucial for this workflow) to a function key, to minimize the keyboard movements while going through a task.

Here's a demo video:
[![IMAGE ALT TEXT](http://img.youtube.com/vi/Tb5ZDLFlR2E/0.jpg)](http://www.youtube.com/watch?v=Tb5ZDLFlR2E "Video Title")

**Comment by govvin** [comment]
It's day 4 of Phase 1 of this effort, and progress steadily with the review -- and it' going much faster than we thought it would be.  Hoping for the same for Phase 2. Capturing status for future reference. 

![ticket 67, day 4 progress](https://user-images.githubusercontent.com/5821688/87214330-02d3d280-c35e-11ea-886c-a6354e7ba7c7.png)

Thank you to the volunteers who are generously helping out with their time and effort - and also for the learning opportunities, with many tips and tricks to quickly resolve mapping issues.

**Comment by govvin** [comment]
#### Phase 2 - 

Review provincial and regional boundary relations in the AOI.  Replicate the boundaries using the Wikimedia Maps layer.

1. Select a geographic area from **[Phase 2 tracker spreadhseet](https://docs.google.com/spreadsheets/d/1Jxh6Mg6mG07WGY3doy1L5gktue2n7oEAXIOrvT7aFcA/edit#gid=255232387)**. Make sure that provincial relations has been fixed, ++before++ tackling the region relation. Update the status to **In progress**. Refer to a map, and ensure that you are working on a relation with **no shared boundary** to a task in progress.
2. With JOSM open, and [Remote Control](https://wiki.openstreetmap.org/wiki/JOSM/RemoteControl) enabled, click on the "RC for PCs" link  to load the latest version of the relation. Avoid using the older link that loads the relation via Overpass Turbo, which may not be a fresh version. You may need to load neighbouring boundary relations, as well.
3. Find and delete nodes and ways wholly added by VMPanes using the following JOSM search filters. Expect relations to break when you do this, which you need to fix afterwards.
    * For nodes: `type:node version:1 user:VMPanes`. 
    * For ways: `type:way user:VMPanes`
5. Use the Wikipedia Maps layer to reconstruct the boundary geometry to the previous version.
6. Find ways that were part of the original relation before March, and recycle them. 
    * You will need to extend/split/add/merge these older ways to fix the gaps in the relation, and add new nodes to match the boundaries found on the Wikipedia Map layer.
    * Click and watch Ian Lopez's demo on how to "recycle" these ways:
      [![Recycling ways - Extend, Split, Merge](https://imgur.com/Q694gFD.gif)](https://youtu.be/2JVASEp6qYk)

6. Once the relation is whole again, run validation and fix and resolve any validation issues you may find. Resolve conflicts with elements deleted in your changeset, in favor of **your version**. Expect other relations to break. Take note of these relations and work on them afterwards.
9. Upload your changes using the changeset comment: 
`Replicate pre-March 2020 boundary geometry, due to rolled back elements coming from OSM incompatible data source. May break relations‼ For details, see: github.com/OSMPH/papercut_fix/issues/67`
11. Mark your task in the spreadsheet as **Fixed**.  Add notes in the spreadsheet, as may be needed.

**Comment by govvin** [comment]
There are no more on-going activities related to this task, and all pending tasks has been completed.

As of 27th June | As of 14th August
--- | ---
![image](https://user-images.githubusercontent.com/5821688/90216698-d9610780-de31-11ea-8e46-4586854cae73.png) | ![image](https://user-images.githubusercontent.com/5821688/90216052-175d2c00-de30-11ea-98ee-a0715841651c.png)

We'd like to acknowledge the active participation of the following volunteers who contributed immensely to completing the tasks related to this rollback effort:
![image](https://user-images.githubusercontent.com/5821688/90216825-30ff7300-de32-11ea-9090-0421b2a1f1fd.png)

This ticket is now closed, but the volunteers are encouraged to leave their comments and insights about the effort in the ticket, for future reference.

**Comment by govvin** [comment]
For additional reference, attached is the archive of the temporary comms channel used by volunteers for internal messaging.
[ticket67-ChatExport2020-08-15.zip](https://github.com/OSMPH/papercut_fix/files/5077713/ticket67-ChatExport2020-08-15.zip)
